{
  "version": "2608.1.1.67",
  "date": "2026-08-23",
  "description": "PUBG Offsets completos para versão 2608.1.1.67 - Xenuine Fix",
  
  "game_globals": {
    "GAME_UWORLD": "0x124D2788",
    "GAME_DECRYPT": "0x10B1C328",
    "GAME_GNAMES": "0x12762990",
    "GAME_GNAMES_OFFSET": "0x10",
    "GAME_ELEMENTS_PER_CHUNK": "0x4040",
    "GAME_GOBJECTS": "0x124931F0"
  },
  
  "decrypt_params": {
    "DECRYPT_ACTOR_OBJID": "0x14",
    "DECRYPT_XOR_KEY": "0x68DEB8FE",
    "DECRYPT_ROR_SHIFT": 28,
    "DECRYPT_FINAL_XOR": "0x65D15EBB",
    "decrypt_cindex_algorithm": "((value ^ 0x68DEB8FE >> 12 & 0x000F0000) | (value ^ 0x68DEB8FE << 20)) ^ _rotr(value ^ 0x68DEB8FE, 28) ^ 0x65D15EBB"
  },
  
  "health_xor_keys": [
    "0xCEC7A58F", "0x9B63B216", "0xCA2B72A5", "0x163848B3",
    "0x34911D0A", "0x23DDBD34", "0x945B3C8", "0xA521A621",
    "0xBBD7A58", "0xB0EF1687", "0xE27503A6", "0x878ADB28",
    "0xBD34D3D5", "0x1693B307", "0xB3099E38", "0xF2C72ACC"
  ],
  
  "world": {
    "OFF_CURRENT_LEVEL": "0xAB0",
    "OFF_GAME_INSTANCE": "0x150",
    "OFF_GAME_STATE": "0x6E0",
    "OFF_TIME_SECONDS": "0x9A0",
    "OFF_AUTHORITY_GAME_MODE": "0x2D0"
  },
  
  "game_instance": {
    "OFF_LOCAL_PLAYERS_DATA": "0x40"
  },
  
  "level_actors": {
    "OFF_ACTORS": "0x1B8",
    "OFF_ACTORS_COUNT": "0x140",
    "OFF_ACTORS_FOR_GC": "0x490",
    "OFF_OBJECT_ID": "0x14",
    "OFF_OBJECT_CLASS": "0x18",
    "OFF_OBJECT_OUTER": "0x8",
    "OFF_OBJECT_NAME_NUMBER": "0x10",
    "OFF_TARRAY_DATA": "0x0",
    "OFF_TARRAY_NUM": "0x8"
  },
  
  "game_state": {
    "OFF_PLAYER_ARRAY": "0x410",
    "OFF_NUM_ALIVE_TEAMS": "0x51C",
    "OFF_FEATURE_REP_OBJECT": "0xD10",
    "OFF_MATCH_ID": "0x548"
  },
  
  "safe_zone": {
    "OFF_SAFE_ZONE_POS": "0xA0",
    "OFF_SAFE_ZONE_RADIUS": "0xAC",
    "OFF_BLUE_ZONE_POS": "0xB0",
    "OFF_BLUE_ZONE_RADIUS": "0xBC"
  },
  
  "player_controller": {
    "OFF_PLAYER_CONTROLLER": "0x30",
    "OFF_ACKNOWLEDGED_PAWN": "0x4A8",
    "OFF_CONTROLLER_PAWN": "0x470",
    "OFF_PLAYER_CAMERA_MANAGER": "0x4D0",
    "OFF_SHOW_MOUSE_CURSOR": "0x658",
    "OFF_VIEW_TARGET": "0x1080",
    "OFF_PLAYER_INPUT": "0x548",
    "OFF_INPUT_YAW_SCALE": "0x64C"
  },
  
  "camera": {
    "OFF_CAMERA_FOV": "0x16C0",
    "OFF_CAMERA_ROT": "0x1C50",
    "OFF_CAMERA_POS": "0x1C5C"
  },
  
  "player_state": {
    "OFF_PLAYER_STATE": "0x430",
    "OFF_PLAYER_NAME": "0x430",
    "OFF_CHARACTER_NAME": "0x10B0",
    "OFF_ACCOUNT_ID": "0x4E8",
    "OFF_TEAM_NUMBER": "0x4F8",
    "OFF_PLAYER_STATISTICS": "0x4FC",
    "OFF_PLAYER_STATE_KILLED_BITS": "0x4D0",
    "OFF_PLAYER_STATE_KILLED_MASK": "0x1",
    "OFF_SQUAD_MEMBER_INDEX": "0x810",
    "OFF_DAMAGE_DEALT_ON_ENEMY": "0x844",
    "OFF_PING": "0x468",
    "OFF_PARTNER_LEVEL": "0x690",
    "OFF_CHARACTER_CLAN_INFO": "0x878"
  },
  
  "actor_components": {
    "OFF_ROOT_COMPONENT": "0x398",
    "OFF_COMPONENT_LOCATION": "0x250",
    "OFF_ACTOR_ROTATION": "0x654",
    "OFF_CHARACTER_MOVEMENT": "0x638",
    "OFF_CAPSULE_COMPONENT": "0x4D0",
    "OFF_COMPONENT_VELOCITY": "0x3E0",
    "OFF_CUSTOM_TIME_DILATION": "0x260",
    "OFF_COMPONENT_TO_WORLD": "0x240"
  },
  
  "character": {
    "OFF_LAST_TEAM_NUM": "0x1008",
    "OFF_SPECTATED_COUNT": "0xFE0",
    "OFF_GENDER": "0xB38",
    "OFF_CHARACTER_STATE": "0x10F8"
  },
  
  "mesh_bones": {
    "OFF_MESH": "0x7A8",
    "OFF_MESH3P": "0x7F0",
    "OFF_MESH_PHYSICS_STATE": "0x488",
    "OFF_STATIC_MESH": "0xAE8",
    "OFF_BONE_COUNT": "0xAF0",
    "OFF_BOUND_BOX": "0x228",
    "OFF_ANIM_SCRIPT_INSTANCE": "0xE30",
    "OFF_B_ALWAYS_CREATE_PHYSICS_STATE": "0x488",
    "OFF_COMPONENT_SPACE_TRANSFORMS_PAOD": "0xAC0",
    "OFF_COMPONENT_SPACE_TRANSFORMS_BASES": [
      "0xAE8", "0xAC0", "0x9C8", "0xA18", "0x9A8", "0xA08", 
      "0x9B0", "0xA68", "0x8E0", "0x980", "0xA00", "0xAA0", 
      "0xAB8", "0xB00"
    ]
  },
  
  "visibility": {
    "OFF_DMA_LAST_SUBMIT_TIME": "0x758",
    "OFF_DMA_LAST_RENDER_TIME_ON_SCREEN": "0x75C",
    "OFF_RECENTLY_RENDERED": "0xBD8",
    "OFF_RECENTLY_RENDERED_MASK": "0x4"
  },
  
  "health": {
    "OFF_HEA_FLAG": "0x166",
    "OFF_HEALTH1": "0x9A4",
    "OFF_HEALTH2": "0x9A0",
    "OFF_HEALTH3": "0x994",
    "OFF_HEALTH4": "0x980",
    "OFF_HEALTH5": "0x995",
    "OFF_HEALTH6": "0x990",
    "OFF_GROGGY_HEALTH": "0x1640",
    "OFF_DBNO_HEALTH": "0x1640",
    "OFF_GROGGY_HEALTH_MAX": "0x14E0"
  },
  
  "dropped_items": {
    "OFF_DROPPED_ITEM": "0x458",
    "OFF_DROPPED_ITEM_GROUP": "0x348",
    "OFF_DROPPED_ITEM_GROUP_UITEM": "0x870",
    "OFF_DROPPED_ITEM_GROUP_ITEM_TABLE": "0xA8",
    "OFF_DROPPED_ITEM_GROUP_UITEM_ID": "0x244",
    "OFF_ITEM_PACKAGE_ITEMS": "0x578",
    "OFF_ITEM_TABLE_ROW_DROPPED_ITEM_MESH_DATA": "0xB0",
    "OFF_ITEM_DEFINITION_ID": "0x240",
    "OFF_ITEM_ROW_ITEM_NAME": "0x18",
    "OFF_ITEM_ROW_ITEM_DETAILED_NAME": "0x48"
  },
  
  "weapons": {
    "OFF_WEAPON_PROCESSOR": "0x968",
    "OFF_EQUIPPED_WEAPONS": "0x1F8",
    "OFF_CURRENT_WEAPON_INDEX": "0x309",
    "OFF_WEAPON_TRAJECTORY_OVERRIDE": "0x1400",
    "OFF_WEAPON_TRAJECTORY_DATA": "0x11B0",
    "OFF_TRAJECTORY_CONFIG": "0x100",
    "OFF_TRAJECTORY_GRAVITY_Z": "0x11A8",
    "OFF_WEAPON_ATTACHMENT_SLOT_RECORDS": "0x818",
    "OFF_WEAPON_ATTACHMENT_ASSET_DATA": "0x828",
    "OFF_WEAPON_ATTACHMENT_DATA": "0x260",
    "OFF_WEAPON_ATTACHED_ITEM_INDICES": "0x838",
    "OFF_ATTACHED_ITEMS": "0x848",
    "OFF_ZEROING_STATE_ARRAY": "0xED8",
    "OFF_DEFAULT_ZEROING_DISTANCES": "0x6B0",
    "OFF_ATTACHMENT_OBJECTS_BOUNDED": "0x1380",
    "OFF_BALLISTIC_CURVE": "0x28",
    "OFF_FLOAT_CURVES": "0x30",
    "OFF_KEYS": "0x60",
    "OFF_BALLISTIC_DRAG_SCALE": "0x480",
    "OFF_BALLISTIC_DROP_SCALE": "0x484",
    "OFF_FIRING_ATTACH_POINT": "0x8B0",
    "OFF_SCOPING_ATTACH_POINT": "0xC88",
    "OFF_WEAPON_CONFIG_WEAPON_CLASS": "0x731",
    "OFF_ACTIVE_SCOPE_SIDE": "0xF98"
  },
  
  "vehicles": {
    "OFF_VEHICLE_RIDER_COMPONENT": "0x2160",
    "OFF_LAST_VEHICLE_PAWN": "0x260",
    "OFF_SEAT_INDEX": "0x220",
    "OFF_REPLICATED_MOVEMENT": "0x78",
    "OFF_VEHICLE_MOVEMENT": "0x468",
    "OFF_WHEELS": "0x318",
    "OFF_WHEEL_LOCATION": "0xF8",
    "OFF_VEHICLE_COMMON_COMPONENT": "0xB30",
    "OFF_FLOATING_VEHICLE_COMMON_COMPONENT": "0x4D8",
    "OFF_VEHICLE_FUEL": "0x2D0",
    "OFF_VEHICLE_FUEL_MAX": "0x2D4",
    "OFF_VEHICLE_HEALTH": "0x2C8",
    "OFF_VEHICLE_HEALTH_MAX": "0x2CC"
  },
  
  "animation": {
    "OFF_PRE_EVAL_PAWN_STATE": "0x630",
    "OFF_B_IS_IN_VEHICLE_CP": "0x820",
    "OFF_B_IS_PARACHUTING_CP": "0x92E",
    "OFF_B_IS_FREEFALLING_CP": "0x92D",
    "OFF_B_EMERGENCY_PICKUP_FLYING_CP": "0x92F",
    "OFF_B_IS_REVIVING_CP": "0x932",
    "OFF_B_IS_SWIMMING_CP": "0x935",
    "OFF_B_IS_DBNO_CP": "0x931",
    "OFF_B_IS_SCOPING_CP": "0x85D",
    "OFF_B_IS_PREPARING_THROW_CP": "0x538",
    "OFF_B_IS_THROWING_CP": "0x938",
    "OFF_B_IS_FLASHED_CP": "0x637",
    "OFF_B_IS_RELOADING_CP": "0x735",
    "OFF_CONTROL_ROTATION_CP": "0x64C",
    "OFF_LEAN_LEFT_ALPHA_CP": "0x694",
    "OFF_LEAN_RIGHT_ALPHA_CP": "0x698",
    "OFF_AIM_OFFSETS": "0x1BB8",
    "OFF_GLOBAL_ANIM_RATE_SCALE": "0xED8"
  },
  
  "ui_hud": {
    "OFF_MY_HUD": "0x4C8",
    "OFF_BLOCK_INPUT_WIDGET_LIST": "0x5C0",
    "OFF_LAYOUT_DATA": "0x38",
    "OFF_OFFSETS": "0x0",
    "OFF_ALIGNMENT": "0x20",
    "OFF_VISIBILITY": "0xA1",
    "OFF_SLOT": "0x30",
    "OFF_MAP_GRID_MAP": "0x4A0"
  },
  
  "static_mesh": {
    "OFF_STATIC_SOCKETS": "0xC0",
    "OFF_STATIC_SOCKET_NAME": "0x28",
    "OFF_STATIC_RELATIVE_SCALE": "0x48",
    "OFF_STATIC_RELATIVE_LOCATION": "0x30",
    "OFF_STATIC_RELATIVE_ROTATION": "0x3C"
  },
  
  "inventory": {
    "OFF_INVENTORY_FACADE": "0x1DE0",
    "OFF_INVENTORY": "0x418",
    "OFF_INVENTORY_ITEMS": "0x5F0",
    "OFF_INVENTORY_ITEM_COUNT": "0x5F8",
    "OFF_EQUIPMENT": "0x400",
    "OFF_EQUIPMENT_ITEMS": "0x568",
    "OFF_ITEM_STACK_COUNT": "0x38",
    "OFF_DURABILITY": "0x1D4",
    "OFF_DURABILITY_MAX": "0x1D0"
  },
  
  "misc": {
    "OFF_TIME_TILL_EXPLOSION": "0x824",
    "OFF_EXPLODE_STATE": "0x648",
    "OFF_TRAINING_MAP_GRID": "0x5F8",
    "OFF_GRAVITY_SCALE": "0x3B4"
  },
  
  "kernel": {
    "EPROCESS_DIR_TABLE_BASE": "0x28"
  }
}
