{
  "GAME_UWORLD":                              "0x12284408",
  "GAME_DECRYPT":                             "0x108ED528",
  "GAME_GNAMES":                              "0x12515880",
  "GAME_GNAMES_OFFSET":                       "0x0",
  "GAME_ELEMENTS_PER_CHUNK":                  "0x3F00",
  "GAME_GOBJECTS":                            "0x12244E60",
  "GAME_GOBJECTS_COUNT":                      "0x12244E68",
  "GAME_GOBJECTS_ARRAY_KEY":                  "0x1",
  "GAME_GOBJECT_ITEM_STRIDE":                 "0x18",

  "OFF_CURRENT_LEVEL":                        "0x9A8",
  "OFF_GAME_INSTANCE":                        "0x8F8",
  "OFF_GAME_STATE":                           "0x6E0",
  "OFF_TIME_SECONDS":                         "0x9A0",
  "OFF_LOCAL_PLAYERS_DATA":                   "0xF0",

  "OFF_ACTORS":                               "0x2A0",
  "OFF_ACTORS_COUNT":                         "0x1C0",
  "OFF_ACTORS_FOR_GC":                        "0x490",
  "OFF_OBJECT_ID":                            "0x18",
  "OFF_OBJECT_OUTER":                         "0x10",
  "OFF_OBJECT_CLASS":                         "0x20",
  "OFF_OBJECT_NAME_NUMBER":                   "0x1C",
  "OFF_TARRAY_DATA":                          "0x0",
  "OFF_TARRAY_NUM":                           "0x8",

  "OFF_PLAYER_ARRAY":                         "0x418",
  "OFF_NUM_ALIVE_TEAMS":                      "0x4D8",
  "OFF_FEATURE_REP_OBJECT":                   "0xD10",

  "OFF_SAFE_ZONE_POS":                        "0xB0",
  "OFF_SAFE_ZONE_RADIUS":                     "0xBC",
  "OFF_BLUE_ZONE_POS":                        "0xC0",
  "OFF_BLUE_ZONE_RADIUS":                     "0xCC",

  "OFF_PLAYER_CONTROLLER":                    "0x38",
  "OFF_ACKNOWLEDGED_PAWN":                    "0x4B8",
  "OFF_CONTROLLER_PAWN":                      "0x408",
  "OFF_PLAYER_CAMERA_MANAGER":                "0x4E0",
  "OFF_SHOW_MOUSE_CURSOR":                    "0x668",
  "OFF_VIEW_TARGET":                          "0xAB0",
  "OFF_CAMERA_FOV":                           "0x1D20",
  "OFF_CAMERA_ROT":                           "0x1D2C",
  "OFF_CAMERA_POS":                           "0x1770",
  "OFF_PLAYER_INPUT":                         "0x558",
  "OFF_INPUT_YAW_SCALE":                      "0x65C",

  "OFF_PLAYER_STATE":                         "0x440",
  "OFF_PLAYER_NAME":                          "0x458",
  "OFF_CHARACTER_NAME":                       "0x1A30",
  "OFF_ACCOUNT_ID":                           "0x958",
  "OFF_TEAM_NUMBER":                          "0x8D0",
  "OFF_SQUAD_MEMBER_INDEX":                   "0x840",
  "OFF_PLAYER_STATISTICS":                    "0x850",
  "OFF_DAMAGE_DEALT_ON_ENEMY":               "0x8E4",
  "OFF_PING":                                 "0x470",
  "OFF_PARTNER_LEVEL":                        "0x6B0",
  "OFF_CHARACTER_CLAN_INFO":                  "0x8E8",
  "OFF_MATCH_ID":                             "0x470",
  "OFF_PLAYER_STATE_KILLED_BITS":             "0x85C",
  "OFF_PLAYER_STATE_KILLED_MASK":             "0x1",

  "OFF_ROOT_COMPONENT":                       "0x1C0",
  "OFF_COMPONENT_LOCATION":                   "0x250",
  "OFF_ACTOR_ROTATION":                       "0x25C",
  "OFF_CHARACTER_MOVEMENT":                   "0x7B0",
  "OFF_CAPSULE_COMPONENT":                    "0x658",
  "OFF_CUSTOM_TIME_DILATION":                 "0x320",
  "OFF_RELATIVE_LOCATION":                    "0x2AC",
  "OFF_COMPONENT_VELOCITY":                   "0x3E0",

  "OFF_LAST_TEAM_NUM":                        "0x1818",
  "OFF_SPECTATED_COUNT":                      "0x17E8",
  "OFF_GENDER":                               "0xB50",
  "OFF_CHARACTER_STATE":                      "0x1E49",
  "OFF_AIM_OFFSETS":                          "0x1C50",

  "OFF_MESH":                                 "0x470",
  "OFF_MESH3P":                               "0x800",
  "OFF_MESH_PHYSICS_STATE":                   "0x488",
  "OFF_COMPONENT_TO_WORLD":                   "0x240",
  "OFF_STATIC_MESH":                          "0xAF8",
  "OFF_BONE_COUNT":                           "0xAF0",
  "OFF_BOUND_BOX":                            "0x228",
  "OFF_ANIM_SCRIPT_INSTANCE":                 "0xE40",
  "OFF_GLOBAL_ANIM_RATE_SCALE":               "0xEE8",

  "OFF_DMA_LAST_SUBMIT_TIME":                 "0x758",
  "OFF_DMA_LAST_RENDER_TIME_ON_SCREEN":       "0x75C",

  "OFF_WEAPON_PROCESSOR":                     "0x9A0",
  "OFF_EQUIPPED_WEAPONS":                     "0x208",
  "OFF_CURRENT_WEAPON_INDEX":                 "0x319",
  "OFF_WEAPON_TRAJECTORY_DATA":               "0x11E8",
  "OFF_WEAPON_TRAJECTORY_OVERRIDE":           "0x1480",
  "OFF_TRAJECTORY_CONFIG":                    "0x108",
  "OFF_TRAJECTORY_GRAVITY_Z":                 "0x1194",
  "OFF_FIRING_ATTACH_POINT":                  "0x8C0",
  "OFF_SCOPING_ATTACH_POINT":                 "0xB00",
  "OFF_ACTIVE_SCOPE_SIDE":                    "0xF98",
  "OFF_ZEROING_STATE_ARRAY":                  "0x1048",
  "OFF_DEFAULT_ZEROING_DISTANCES":            "0x590",
  "OFF_BALLISTIC_CURVE":                      "0x28",
  "OFF_FLOAT_CURVES":                         "0x38",
  "OFF_KEYS":                                 "0x60",
  "OFF_BALLISTIC_DRAG_SCALE":                 "0x488",
  "OFF_BALLISTIC_DROP_SCALE":                 "0x48C",

  "OFF_ATTACHED_ITEMS":                       "0x858",
  "OFF_WEAPON_ATTACHMENT_SLOT_RECORDS":       "0x828",
  "OFF_WEAPON_ATTACHMENT_ASSET_DATA":         "0x838",
  "OFF_WEAPON_ATTACHMENT_DATA":               "0x260",
  "OFF_WEAPON_ATTACHED_ITEM_INDICES":         "0x848",
  "OFF_ATTACHMENT_OBJECTS_BOUNDED":           "0x1390",
  "OFF_DISPROVED_PARTICLE_FIELD":             "0x1508",
  "OFF_WEAPON_CONFIG_WEAPON_CLASS":           "0x5FC",
  "OFF_ELAPSED_COOKING_TIME":                 "0xC48",

  "OFF_LAST_UPDATE_VELOCITY":                 "0x3E0",
  "OFF_EYES":                                 "0x75C",
  "OFF_REPLICATED_MOVEMENT":                  "0x88",

  "OFF_VEHICLE_MOVEMENT":                     "0x478",
  "OFF_VEHICLE_RIDER_COMPONENT":              "0x20D0",
  "OFF_LAST_VEHICLE_PAWN":                    "0x270",
  "OFF_SEAT_INDEX":                           "0x230",
  "OFF_VEHICLE_COMMON_COMPONENT":             "0xB40",
  "OFF_FLOATING_VEHICLE_COMMON_COMPONENT":    "0x4E8",
  "OFF_VEHICLE_FUEL":                         "0x2E0",
  "OFF_VEHICLE_FUEL_MAX":                     "0x2E4",
  "OFF_VEHICLE_HEALTH":                       "0x2D8",
  "OFF_VEHICLE_HEALTH_MAX":                   "0x2DC",

  "OFF_WHEELS":                               "0x328",
  "OFF_WHEEL_LOCATION":                       "0x100",
  "OFF_DAMPING_RATE":                         "0x4C",
  "OFF_SHAPE_RADIUS":                         "0x40",

  "OFF_PRE_EVAL_PAWN_STATE":                  "0x638",
  "OFF_CURRENT_AMMO_DATA":                    "0xEF8",
  "OFF_RECOIL_ADS_ROTATION_CP":               "0x824",
  "OFF_CONTROL_ROTATION_CP":                  "0x654",
  "OFF_LEAN_LEFT_ALPHA_CP":                   "0x69C",
  "OFF_LEAN_RIGHT_ALPHA_CP":                  "0x6A0",
  "OFF_RECOIL_VALUE_VECTOR":                  "0x1104",
  "OFF_VERTICAL_RECOVERY":                    "0x1190",

  "OFF_IS_IN_VEHICLE_CP":                     "0x820",
  "OFF_IS_PARACHUTING_CP":                    "0x92E",
  "OFF_IS_FREEFALLING_CP":                    "0x92D",
  "OFF_EMERGENCY_PICKUP_FLYING_CP":           "0x92F",
  "OFF_IS_REVIVING_CP":                       "0x932",
  "OFF_IS_SWIMMING_CP":                       "0x935",
  "OFF_IS_DBNO_CP":                           "0x931",
  "OFF_IS_DBNO0":                             "0x34EA",
  "OFF_IS_DBNO1":                             "0x34E8",
  "OFF_IS_DBNO2":                             "0x34E9",
  "OFF_IS_SCOPING_CP":                        "0x85D",
  "OFF_IS_PREPARING_THROW_CP":                "0x540",
  "OFF_IS_THROWING_CP":                       "0x938",
  "OFF_IS_FLASHED_CP":                        "0x63F",
  "OFF_IS_RELOADING_CP":                      "0x73D",
  "OFF_VTABLE":                               "0x970",

  "OFF_STATIC_SOCKETS":                       "0xC8",
  "OFF_STATIC_SOCKET_NAME":                   "0x30",
  "OFF_STATIC_RELATIVE_SCALE":                "0x50",
  "OFF_STATIC_RELATIVE_LOCATION":             "0x38",
  "OFF_STATIC_RELATIVE_ROTATION":             "0x44",

  "OFF_INVENTORY_FACADE":                     "0x19A8",
  "OFF_INVENTORY":                            "0x430",
  "OFF_INVENTORY_ITEMS":                      "0x698",
  "OFF_INVENTORY_ITEM_COUNT":                 "0x6A0",
  "OFF_INVENTORY_ITEM_TAG_ITEM_COUNT":        "0x38",
  "OFF_EQUIPMENT":                            "0x418",
  "OFF_ITEMS_ARRAY":                          "0x578",
  "OFF_ITEM_PACKAGE_ITEMS":                   "0x580",
  "OFF_DURABILITY":                           "0x1E4",
  "OFF_DURABILITY_MAX":                       "0x1E0",
  "OFF_ITEM_STACK_COUNT":                     "0x40",

  "OFF_DROPPED_ITEM":                         "0x460",
  "OFF_DROPPED_ITEM_GROUP":                   "0x430",
  "OFF_DROPPED_ITEM_GROUP_UITEM":             "0x880",
  "OFF_DROPPED_ITEM_GROUP_ITEM_TABLE":        "0xA8",
  "OFF_DROPPED_ITEM_GROUP_UITEM_ID":          "0x240",
  "OFF_DROPPED_ITEM_GROUP_ATTACHED_ITEMS":    "0x98",
  "OFF_DROPPED_ITEM_GROUP_COMPONENT_MAP":     "0xF0",
  "OFF_DROPPED_ITEM_GROUP_COMPONENTS":        "0x148",
  "OFF_ACTOR_BLUEPRINT_CREATED_COMPONENTS":   "0x290",
  "OFF_ACTOR_INSTANCE_COMPONENTS":            "0x40",
  "OFF_SCENE_COMPONENT_ATTACH_PARENT":        "0x200",
  "OFF_SCENE_COMPONENT_ATTACH_CHILDREN":      "0x380",
  "OFF_ITEM_TABLE_ROW_DROPPED_ITEM_MESH_DATA":"0xB0",
  "OFF_ITEM_ROW_ITEM_NAME":                   "0x18",
  "OFF_ITEM_ROW_ITEM_DETAILED_NAME":          "0x48",
  "OFF_ITEM_ROW_ITEM_CLASS":                  "0x248",
  "OFF_EQUIPABLE_ITEM_LEVEL_TYPE":            "0x3D3",

  "OFF_MY_HUD":                               "0x4D8",
  "OFF_BLOCK_INPUT_WIDGET_LIST":              "0x5C8",
  "OFF_WORLD_TO_MAP":                         "0x320",
  "OFF_LAYOUT_DATA":                          "0x40",
  "OFF_OFFSETS":                              "0x0",
  "OFF_ALIGNMENT":                            "0x20",
  "OFF_VISIBILITY":                           "0xA9",
  "OFF_SELECT_MINIMAP_SIZE_INDEX":            "0x548",
  "OFF_SLOT":                                 "0x38",
  "OFF_WIDGET_STATE_MAP":                     "0x548",
  "OFF_CURRENT_MINIMAP_VIEW_SCALE_1D":        "0x464",
  "OFF_LAST_MINIMAP_POS":                     "0x478",
  "OFF_MINIMAP":                              "0x478",
  "OFF_TRAINING_MAP_GRID":                    "0x600",
  "OFF_MAP_GRID_MAP":                         "0x4A8",

  "OFF_LAST_DAMAGE":                          "0x1AA0",
  "OFF_ANTI_CHEAT_CHARACTER_SYNC_MANAGER":    "0x1420",
  "OFF_BLUE_BLOCKER_GAUGE_TOTAL_MAX":         "0x10",
  "OFF_DBNO_HEALTH":                          "0x19A0",
  "OFF_DBNO_HEALTH_MAX":                      "0x1830",

  "OFF_TIME_TILL_EXPLOSION":                  "0x834",
  "OFF_EXPLODE_STATE":                        "0x628",
  "OFF_MORTAR_ROTATION":                      "0x520",
  "OFF_MORTAR_ENTITY":                        "0xB0",

  "OFF_FIRST_PERSON_CAMERA":                  "0xF68",
  "OFF_SUB_INSTANCES":                        "0xE38",
  "OFF_SUB_ANIM_CACHED_PARENT_INSTANCE":      "0x3A0",
  "OFF_SUB_ANIM_CHARACTER_REFERENCE":         "0x67C",
  "OFF_IK_RECOIL_ADS_ROTATION":               "0x3F0",

  "OFF_PHYSICS_SCENE":                        "0x1E8",
  "OFF_MPHYSX_SCENE":                         "0xD0",
  "OFF_RIGID_DYNAMICS":                       "0x300",
  "OFF_B_ALWAYS_CREATE_PHYSICS_STATE":        "0x498",

  "OFF_RECENTLY_RENDERED":                    "0xBE8",
  "OFF_RECENTLY_RENDERED_MASK":               "0x4",

  "OFF_GRAVITY_SCALE":                        "0x3BC",
  "OFF_AUTHORITY_GAME_MODE":                  "0x1B0",

  "OFF_HEA_FLAG":                             "0x166",
  "OFF_HEALTH1":                              "0x9A4",
  "OFF_HEALTH2":                              "0x9A0",
  "OFF_HEALTH3":                              "0x994",
  "OFF_HEALTH4":                              "0x980",
  "OFF_HEALTH5":                              "0x995",
  "OFF_HEALTH6":                              "0x990",
  "OFF_GROGGY_HEALTH":                        "0x1E90",

  "OFF_COMPONENT_SPACE_TRANSFORMS_PAOD":      "0xAC0",
  "SCAN_MESH_TARRAY_MIN":                     "0x80",
  "SCAN_MESH_TARRAY_MAX":                     "0xD00",

  "DECRYPT_NAME_INDEX_ROR":                   "0x1",
  "DECRYPT_NAME_INDEX_XOR_KEY1":              "0x1F65BC48",
  "DECRYPT_NAME_INDEX_XOR_KEY2":              "0xB91AE7CF",
  "DECRYPT_NAME_INDEX_XOR_KEY3":              "0x70000",
  "DECRYPT_NAME_INDEX_RVAL":                  "0x1D",
  "DECRYPT_NAME_INDEX_SVAL":                  "0x13",
  "DECRYPT_NAME_INDEX_DVAL":                  "0xD",

  "DECRYPT_ACTOR_OBJID":                      "0x18",
  "DECRYPT_XOR_KEY":                          "0x1F65BC48",
  "DECRYPT_ROR_SHIFT":                        "29",
  "DECRYPT_FINAL_XOR":                        "0xB91AE7CF"
}
